---
title: "experiment_methods"
author: "YLU"
date: "2024-05-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, error=FALSE, warning = FALSE)
source("../library.R")
```

```{r}
data <- read_csv("../data/example_data_for_visualization.csv")
mean_VOT <- data %>% 
  group_by(label, type) %>% 
  summarise(mean_vot = mean(vot)) %>% 
  ungroup()

f_bar <- mean_VOT %>% 
  ggplot(aes(x=label, y=mean_vot, fill=label)) +
  geom_bar(stat="identity") +
  facet_grid(~ type) +
  scale_fill_brewer(palette="Set1")
  
f_bar
```
From the above analysis, it seems that VOT is longer for voiceless sounds than voiced sounds. There does not seem to be differences across different word classes.

```{r}
f_scatter <- data %>% 
  filter(stop %in% c("B", "P")) %>% 
  ggplot(aes(x=vot, y=vdur, color=stop)) +
  geom_point(size=1) +
  scale_color_manual(values=c("B"="red", "P"="blue")) +
  stat_ellipse(level=0.95, geom="polygon", alpha=0.2)

f_scatter
```
From the above analysis, VOT seems to be a strong indicator for the voicing contrast. However, vowel duration is not quite useful. These two categories overlap with each other by large.



